apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_vote:latest
        name: vote
        ports:
        - containerPort: 80
          name: vote
      imagePullSecrets:
      - name: ecrsecret