apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_worker:latest
        name: worker
