pipeline {
    agent {    
        kubernetes {
          yaml '''
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: docker
                image: docker:latest
                command:
                - cat
                tty: true
                volumeMounts:
                 - mountPath: /var/run/docker.sock
                   name: docker-sock

              - name: snyk-python
                image: snyk/snyk-cli:python-3
                command:
                - /bin/cat
                tty: true

              - name: snyk-docker
                image: snyk/snyk:docker
                command:
                - /bin/cat
                tty: true
                env:
                - name: DOCKER_SCAN_SUGGEST
                  value: false
                volumeMounts:
                 - mountPath: /var/run/docker.sock
                   name: docker-sock

              volumes:
              - name: docker-sock
                hostPath:
                  path: /var/run/docker.sock

            '''
        }
    }
    environment {
        ECR_REPO_REGISTRY = '762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp'
    }
    stages {
        
        stage ('Synk Scan') {
            failFast true
            // environment {
            //     SYNK_TOKEN = 'f1ab0cbe-cf59-4834-9429-a0b4057e2e4a'
            // }
                  parallel {
                    stage('dependency scan') {
                        steps {
                            container('snyk-python') {
                                sh """
                                    pip install -r jenkins-votingapp/vote/requirements.txt
                                    snyk auth f1ab0cbe-cf59-4834-9429-a0b4057e2e4a
                                    snyk test --json \
                                    --file=jenkins-votingapp/vote/requirements.txt \
                                    --severity-threshold=critical \
                                    --org=mustafa.aykon \
                                    --project-name=mustafaaykon/jenkins-votingapp
                                """
                                }
                        }
                    }
                    stage('docker scan') {
                        steps {
                            container('snyk-docker') {
                            sh """
                                docker build -t jenkins_votingapp_vote ./jenkins-votingapp/vote
                                snyk auth f1ab0cbe-cf59-4834-9429-a0b4057e2e4a
                                snyk container test jenkins_votingapp_vote:latest --file=jenkins-votingapp/vote/Dockerfile --severity-threshold=critical --org=mustafa.aykon --project-name=mustafaaykon/jenkins-votingapp
                            """
                                }
                            }
                        }
                    }
            }   

        stage ('Install & Login') {
            steps {
                script {
                        container('docker') {
                            sh 'apk add --no-cache \
                                npm \
                                python3 \
                                py3-pip \
                                && pip3 install --upgrade pip \
                                && pip3 install --no-cache-dir \
                                awscli \
                                && rm -rf /var/cache/apk/*'
                            sh 'aws --version'
                            sh "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 762247940679.dkr.ecr.us-east-1.amazonaws.com"
                        }
                }
            }
        }

        stage ('Build') {
            steps {
                    script {
                        container('docker') {                          

                            sh 'docker build -t 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_vote ./jenkins-votingapp/vote'
                            sh 'docker build -t 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_result ./jenkins-votingapp/result'
                            sh 'docker build -t 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_worker ./jenkins-votingapp/worker'

                            sh 'docker tag 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_vote:latest 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_vote:""$BUILD_ID""'
                            sh 'docker tag 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_result:latest 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_result:""$BUILD_ID""'
                            sh 'docker tag 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_worker:latest 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_worker:""$BUILD_ID""'
                                                    
                        }                       
                }       
            }
        }

        stage ('Push to ECR') {
            steps {
                script {
                    container('docker') {

                            sh 'docker push 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_vote:latest'
                            sh 'docker push 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_vote:""$BUILD_ID""'
                            sh 'docker push 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_result:latest'
                            sh 'docker push 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_result:""$BUILD_ID""'
                            sh 'docker push 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_worker:latest'
                            sh 'docker push 762247940679.dkr.ecr.us-east-1.amazonaws.com/jenkins_votingapp_worker:""$BUILD_ID""' 
                        }
                    }
                }
            }

    }    
}
